variables:
  NUGET_PATH: 'C:\Tools\Nuget\nuget.exe'
  NUGET_PACKAGES: 'C:\Tools\Nuget\packages'
  MSBUILD_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\msbuild.exe'
  XUNIT_PATH: packages\xunit.runner.console.2.4.1\tools\net461
  UNITTEST_FOLDER: '.\Atomex.Client.Wpf.Tests\bin\Release\'
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - build
  - test

build:
  stage: build
  only:
    - branches
  script:
    - 'dotnet restore --packages "$env:NUGET_PACKAGES"'
    - '& "$env:NUGET_PATH" restore'
    - '& "$env:MSBUILD_PATH" /p:Configuration=Release /clp:ErrorsOnly'
  artifacts:
    expire_in: 2 days
    paths:
      - '$env:UNITTEST_FOLDER'
      - '.\$env:XUNIT_PATH\*.*'

test:
  stage: test
  only:
    - branches
  script:
    - '& "$env:XUNIT_PATH\xunit.console.exe" "$env:UNITTEST_FOLDER\Atomex.Client.Wpf.Tests.dll"'
  dependencies:
    - build 