version: 1.0.{build}

branches:
 only:
   - master
    
skip_tags: true

image: Visual Studio 2017

clone_script:
  - cmd: git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
  - cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%

build_script:
  - dotnet restore
  - nuget restore
  - msbuild /p:Configuration="Release"  /clp:ErrorsOnly'
  - msbuild .\Atomix.Client.Wpf.Installer\Atomix.Client.Wpf.Installer.wixproj /p:Configuration="Release" /clp:ErrorsOnly'

after_build:
  - ps: .\InstallSelfSignedCert.ps1
  - ps: Set-AuthenticodeSignature -FilePath .\Atomix.Client.Wpf.Installer\bin\Release\Atomix.Wallet.msi -Certificate @(gci Cert:\LocalMachine\Root -DnsName "atomix.me" -codesigning)[0]

artifacts:
  - path: .\Atomix.Client.Wpf.Installer\bin\Release\Atomix.Wallet.msi

deploy:
  release: v$(appveyor_build_version)
  description: 'Release description.'
  provider: GitHub
  auth_token:
    secure: tu9uVOIo1aeDV/0cdsLYA7Dbs75q8ogSTe8y9vPACH8zb1G417/RVwpqq+ZwT4rV
  artifact: /.*/
  draft: true
  prerelease: true
  on:
    branch: master
